title = "Terminal Blog"
baseURL = "https://example.com/"
locale = "en-us"
disableKinds = ["taxonomy", "term"]

[module]
  [[module.imports]]
    path = "github.com/dotzenith/terminal-blog"

[markup]
  [markup.highlight]
    noClasses = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4

[menus]
  [[menus.main]]
    name = "Home"
    pageRef = "/"
    weight = 10
  [[menus.main]]
    name = "Posts"
    pageRef = "/posts"
    weight = 20
  [[menus.main]]
    name = "About"
    pageRef = "/about"
    weight = 30

[params]
  description = "A focused Hugo theme with a framed terminal interface."
  defaultColor = "auto"

  [params.author]
    name = "Terminal Author"
    intro = "Occasionally, I think"
    description = "A small place for long-form notes from the end of the internet."

  [params.analytics]
    umamiWebsiteID = ""

  [params.socialImage]
    endpoint = "https://og.danshu.co/generate"
    site = "example.com"
    defaultSize = 50
